import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Page.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          <Link href="/todos">Go to SSR page</Link>
          <br />
          <Link href="/static">Go to static page</Link>
        </p>
      </main>
    </div>
  );
};

export default Home;
